# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oxIzQT2yC1ICchdc2VGkpptWjC-lzOdY
"""

!apt-get install unrar

!unrar x "/content/Brain Tumor.rar"

!ls /content

!unrar x "/content/Brian Tumor.rar"

!ls /content

# ==============================
# INSTALL LIBRARIES
# ==============================
!pip install torch torchvision

import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
from torch.utils.data import DataLoader

device = "cuda" if torch.cuda.is_available() else "cpu"

# ==============================
# PATHS
# ==============================
train_path = "/content/Brian Tumor/Original/train"
val_path   = "/content/Brian Tumor/Original/val"
test_path  = "/content/Brian Tumor/Original/test"

# ==============================
# TRANSFORMS
# ==============================
transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

train_data = datasets.ImageFolder(train_path, transform=transform)
val_data   = datasets.ImageFolder(val_path, transform=transform)
test_data  = datasets.ImageFolder(test_path, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
val_loader   = DataLoader(val_data, batch_size=32)
test_loader  = DataLoader(test_data, batch_size=32)

# ==============================
# MODEL
# ==============================
model = models.efficientnet_b0(weights="IMAGENET1K_V1")
model.classifier[1] = nn.Linear(1280, len(train_data.classes))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

# ==============================
# TRAIN
# ==============================
EPOCHS = 5

for epoch in range(EPOCHS):
    model.train()
    total_loss = 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        output = model(images)
        loss = criterion(output, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss:", total_loss)

# ==============================
# TEST ACCURACY
# ==============================
model.eval()
correct = total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, pred = torch.max(outputs, 1)
        correct += (pred == labels).sum().item()
        total += labels.size(0)

acc = 100 * correct / total
print("🔥 EfficientNet ORIGINAL Accuracy:", acc)

import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
from torch.utils.data import DataLoader

device = "cuda" if torch.cuda.is_available() else "cpu"

train_path = "/content/Brian Tumor/Enhanced/train"
val_path   = "/content/Brian Tumor/Enhanced/val"
test_path  = "/content/Brian Tumor/Enhanced/test"

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

train_data = datasets.ImageFolder(train_path, transform=transform)
val_data   = datasets.ImageFolder(val_path, transform=transform)
test_data  = datasets.ImageFolder(test_path, transform=transform)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader  = DataLoader(test_data, batch_size=32)

model = models.efficientnet_b0(weights="IMAGENET1K_V1")
model.classifier[1] = nn.Linear(1280, len(train_data.classes))
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

for epoch in range(5):
    model.train()
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        loss = criterion(model(images), labels)
        loss.backward()
        optimizer.step()

model.eval()
correct = total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        _, pred = torch.max(model(images), 1)
        correct += (pred == labels).sum().item()
        total += labels.size(0)

acc = 100 * correct / total
print("🔥 EfficientNet ENHANCED Accuracy:", acc)







